# Generated by Django 2.1.7 on 2019-05-03 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('relationship', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=20)),
                ('office_phone', models.CharField(max_length=20)),
                ('cellphone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=80)),
                ('marital_status', models.CharField(max_length=30)),
                ('religion', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('occupation', models.CharField(max_length=30)),
                ('can_locate', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=1)),
                ('how_locate', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('house_time', models.IntegerField()),
                ('why', models.CharField(max_length=100)),
                ('needs', models.CharField(max_length=300)),
                ('is_helped', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=1)),
                ('who_helps', models.CharField(max_length=150)),
                ('is_regular', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=1)),
                ('specify', models.CharField(max_length=50)),
                ('alternative_person', models.CharField(max_length=50)),
                ('alternative_person_phone', models.CharField(max_length=20)),
                ('alternative_person_email', models.EmailField(max_length=80)),
                ('where_alternative_person', models.CharField(max_length=50)),
                ('margin', models.CharField(max_length=50)),
                ('arguments', models.CharField(max_length=100)),
                ('leave_caregiver', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=1)),
                ('why_leave', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('begin_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='interview.Interview')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('occupation', models.CharField(max_length=30)),
                ('scholarship', models.CharField(max_length=30)),
                ('marital_status', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('genre', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('birth_location', models.CharField(max_length=80)),
                ('adults_shared_location', models.IntegerField()),
                ('relationship_adults', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='interview.Interview')),
                ('how', models.CharField(max_length=100)),
                ('know_person', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=1)),
                ('when_know', models.CharField(max_length=10)),
                ('specification', models.CharField(max_length=300)),
                ('services', models.CharField(max_length=300)),
                ('actions', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='interview.Interview')),
                ('family_rate', models.IntegerField()),
                ('family_why', models.CharField(max_length=300)),
                ('disease', models.CharField(max_length=300)),
                ('actions', models.CharField(max_length=300)),
                ('reunion', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=1)),
                ('reunion_agreements', models.CharField(max_length=300)),
                ('not_reunion', models.CharField(max_length=300)),
                ('indications', models.CharField(max_length=300)),
                ('conceive', models.CharField(max_length=150)),
                ('represent', models.CharField(max_length=300)),
                ('feelings', models.CharField(max_length=300)),
                ('situation', models.CharField(max_length=300)),
                ('comments', models.CharField(max_length=300)),
                ('alternatives', models.CharField(max_length=200)),
                ('motivation', models.CharField(max_length=200)),
                ('atention', models.CharField(choices=[('1', 'Temprana'), ('2', 'Intermedia'), ('3', 'Tardía')], max_length=1)),
                ('atention_why', models.CharField(max_length=100)),
                ('therapy', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=1)),
                ('therapy_why', models.CharField(max_length=200)),
                ('talk', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=1)),
                ('talk_how', models.CharField(max_length=20)),
                ('hard_part', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('adult', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='interview.Adult')),
                ('name', models.CharField(max_length=50)),
                ('relationship', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=20)),
                ('office_phone', models.CharField(max_length=20)),
                ('cellphone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('how', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='caregiver',
            name='adult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.Adult'),
        ),
    ]
