# Generated by Django 2.1.7 on 2019-05-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='nationality',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='adult',
            name='religion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
