# Generated by Django 2.1.7 on 2019-05-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20190503_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='know_person',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2),
        ),
    ]
