# Generated by Django 2.1.7 on 2019-05-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_auto_20190503_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='email',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
