# Generated by Django 2.1.7 on 2019-05-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_tutor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='responsibilities',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.EmailField(blank=True, max_length=80, null=True),
        ),
    ]
