# Generated by Django 2.1.7 on 2019-05-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_caregiver_alternative_person_why'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='atention',
            field=models.CharField(choices=[('1', 'Temprana'), ('2', 'Intermedia'), ('3', 'Tardía')], max_length=3),
        ),
    ]
