# Generated by Django 2.2.2 on 2019-06-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_auto_20190612_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='phase',
            field=models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
    ]
