# Generated by Django 2.1.7 on 2019-03-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valoracion', '0002_auto_20190329_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='begin_date',
            field=models.DateField(),
        ),
    ]
