# Generated by Django 2.1.7 on 2019-03-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
