# Generated by Django 2.1.7 on 2019-04-04 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('valoracion', '0003_auto_20190329_2008'),
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afirmation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Afirmation')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_date', models.DateField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('valoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valoracion.Valoracion')),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='instrument_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.InstrumentAnswer'),
        ),
        migrations.AddField(
            model_name='answers',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Option'),
        ),
    ]
