# Generated by Django 2.2.2 on 2019-06-13 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_auto_20190503_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_points', models.IntegerField()),
                ('max_points', models.IntegerField()),
                ('rank', models.CharField(max_length=50)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument')),
            ],
        ),
    ]
