# Generated by Django 2.1.7 on 2019-03-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_instrument_is_complex'),
    ]

    operations = [
        migrations.AddField(
            model_name='afirmation',
            name='is_inverse',
            field=models.BooleanField(default=False),
        ),
    ]
