# Generated by Django 2.1.7 on 2019-04-04 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_instrument_instrucciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='instrucciones',
            new_name='instructions',
        ),
    ]
