# Generated by Django 2.1.7 on 2019-03-07 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_afirmation_is_inverse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afirmation',
            old_name='instruments',
            new_name='instrument',
        ),
    ]
