# Generated by Django 2.2.2 on 2019-06-12 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_auto_20190612_1827'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='caregiver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.Caregiver'),
        ),
    ]
