# Generated by Django 2.1.7 on 2019-03-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(default='cuidador', max_length=20),
        ),
    ]
