# Generated by Django 2.1.7 on 2019-04-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190325_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('psicologo', 'Psicólogo'), ('cuidador', 'Cuidador')], max_length=20),
        ),
    ]
